---

- name: dnf_automatic Tasks
  tags:
    - dnf_automatic_install
    - dnf_automatic_config
    - dnf_automatic
  block:
    - name: Set dependency variables
      ansible.builtin.include_vars: "{{ item }}"
      loop:
        - "{{ ansible_os_family }}.yml"
        - "{{ ansible_os_family }}/{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - name: Install tasks
      ansible.builtin.import_tasks: install.yml
    - name: Configration tasks
      ansible.builtin.import_tasks: config.yml
    - name: Service tasks
      ansible.builtin.import_tasks: service.yml
  rescue:
    - name: Print Error
      ansible.builtin.debug:
        msg: "Unsupport platform or error occurred due to some reason."
      failed_when: true
