---

- name: Service tasks
  become: true
  tags:
    - dnf_automatic_service
    - dnf_automatic
  block:
    - name: Ensure service
      ansible.builtin.service:
        name: "{{ dnf_automatic_service_name }}"
        state: "{{ dnf_automatic_service_ensure }}"
        enabled: "{{ dnf_automatic_service_enable }}"
